[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = false
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
]
solc = "0.8.24"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 200
# Allow deploy script to write .env.deployed output file
fs_permissions = [{ access = "read-write", path = "./" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
